// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCixMOjqL-h0yxm9Xbtv2TQ6P2qXuynyhE',
    appId: '1:512685603987:web:b83c69aed94f6f23b36166',
    messagingSenderId: '512685603987',
    projectId: 'doc-in-unasam-app',
    authDomain: 'doc-in-unasam-app.firebaseapp.com',
    storageBucket: 'doc-in-unasam-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQHwutBaZSR8gbzgZ5wgexVjB6aiwBsFU',
    appId: '1:512685603987:android:aafecef26394888db36166',
    messagingSenderId: '512685603987',
    projectId: 'doc-in-unasam-app',
    storageBucket: 'doc-in-unasam-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4ie3XvLt2qamYxPdhvDfaUO-yyLj2GIc',
    appId: '1:512685603987:ios:def472e69885bc39b36166',
    messagingSenderId: '512685603987',
    projectId: 'doc-in-unasam-app',
    storageBucket: 'doc-in-unasam-app.firebasestorage.app',
    iosBundleId: 'com.bubu.profeUnasam',
  );
}
